### ISSUE TITLE
Bekomme nur fehlerhafte Daten

### ISSUE THREAD

**Issue by laimermic** [micronano0/ESP8266-NodeMCU-KAIFA-SmartMeter-Reader-STV-#1]
Hallo!
Hat noch jemand das Problem, dass nur fehlerhafte Daten vom Smartmeter kommen?
Ich habe einen Kaifa MA309M mit Netzanbieter VKW und bekomme seit neuestem nichts brauchbares mehr. Der receiveBufferIndex ist bei jeder Nachricht ein anderer, aber nie so wie er sein sollte. Vor ein paar Tagen hat alles funktioniert und auf einmal ging es nicht mehr. Hat dieses Problem noch jemand? Bei den Leuten, bei denen es funktioniert: In welchem Intervall bekommt ihr Daten vom Smartmeter?

**Comment by da-winci** [comment]
Servus,
Was heißt fehlerhafte Daten bei dir?
Habe auch einen VKW MA309M Smartmeter mit Kundenschnittstelle seit heute aktiv.
Bei mir kommen Daten an, aber scheinen invalide zu sein.
Wie schauen die Daten bei dir aus. Bzw. wie lange sind deine?

Siehe -> https://github.com/FKW9/esp-smartmeter-netznoe/issues/10

**Comment by laimermic** [comment]
Ich habe noch nicht geschaut was für daten genau kommen, habe mir nur den receiveBufferIndex angesehen, und der ist bei mir immer unterschiedlich (kenne mich in diesem Bereich nicht besonders aus : \ )

Habe auch ein bisschen den Verdacht, dass die VKW hierbei das Problem ist. Seit dem 1. Juli kommen da nämlich keine Daten mehr ins Webportal von vorarlbergnetz und der Zählerstatus wird als NONSMART dargestellt. Gleichzeitig kamen auch nur noch "fehlerhafte" Daten von der Kundenschnittstelle (zuvor hat alles funktioniert). Bei der VKW wurde mir gesagt, dass sie momentan Probleme wegen der Monatsumstellung haben😆. Vielleicht wurde die Kundenschnittstelle durch die Probleme bei vorarlbergnetz deaktiviert? Warum dann aber überhaupt noch Daten kommen, kann ich mir aber auch nicht erklären (ist nur eine Theorie).

Seit neuestem geht das Webportal wieder (Zähler wird immer noch als NONSMART dargestellt). Werde es in nächste Zeit nochmals probieren, und versuchen ein paar mehr daten zu bekommen...

![grafik](https://github.com/micronano0/ESP8266-NodeMCU-KAIFA-SmartMeter-Reader-STV-/assets/74672993/dd10fdf5-7894-4886-8c33-d6abb6a25b03)


Bei mir schlägt der Code hier fehl:
```c++
if (receiveBufferIndex >= 300 && nachricht1_startbyte == 104 && nachricht1_endebyte == 22) {

} else {
      Serial.print("\n\nERROR - Nachricht fehlerhaft ==> warte auf naechsten Block\n");
}
```

**Comment by da-winci** [comment]
Hast du einen TTL-USB Adapter womit du die Daten der MBus Schnittstelle abgreifen kannst?
Dann könnten wir unsere Daten vergleichen.
![Dataframes](https://github.com/micronano0/ESP8266-NodeMCU-KAIFA-SmartMeter-Reader-STV-/assets/16208927/88debc26-5a3c-430b-bea1-c500b5fa46c7)

**Comment by laimermic** [comment]
Ne, ich bin mit nem M-Bus Slave Click von Mikroe und nem ESP8266 unterwegs...

Allerdings müsste ich noch einen irgendwo rumliegen haben...ich werde mal damit versuchen, Daten auszulesen
